spring.application.name=hirepath-backend
# Server
server.port=${PORT:8080}

# Database - PostgreSQL
spring.datasource.url=${jdbc:postgresql://dpg-d7kf69pkh4rs7394qdag-a:5432/hirepath_db_y9ba}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Prevent circular reference error (Spring Boot 3 safety)
spring.main.allow-circular-references=true

# File upload settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# CORS Configuration for Render
server.servlet.context-path=/
